### ISSUE TITLE
RBD expression filter

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#41]
@jbloom attached plot adds RBD expression filter, it definitely improves correlation across the board but XBB15 RBD lenti vs XBB15 yeast still does not improve to the point one would expect (?) Dimeric ACE2 data for lenti RBD library as well as full spike data correlations with yeast look great though, maybe that experiment is just not as good. I do though like having RBD expression filter here.

Also, I think the clipping on the plots we have on the repo does not look good, I think I'm going to change those clip values like in the attached if it's fine with you. 
[affinity_corr.html.zip](https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/files/12722421/affinity_corr.html.zip)

**Comment by jbloom** [comment]
Changing the clipping is fine. Just be sure to specify this and any other filter values in the `snakemake` `params`, not in the code itself, so we can remember how they are being clipped easily.

I don't think we need a RBD expression filter, what does that add exactly? If there is a benefit we can add it, but the benefit is not obvious to me.

The issue I was noting in the paper is the poor correlation for the XBB.1.5 RBD pseudovirus DMS with the yeast display RBD DMS. Looking at the points, a lot of this seems to be due to the DMS giving dubious estimates to mutations such as N501K. Look at the points in the lower right of the plot: almost all of them seem to be caused by dubious measured effects of the RBD pseudovirus DMS that have very disparate measurements between libraries. I think we should try to figure out what is going on with that, and if we can't determine the cause potentially add a new filter. Right now we are showing a heat map that for instance indicates N501K is highly affinity enhancing, which seems dubious.
