### ISSUE TITLE
Functional correlations

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#47]
Plot mutation-level functional score correlations between Lib1/Lib2 for XBB.1.5 full spike and with XBB.1.5 RBD and BA.2 libaries.

**Comment by Bernadetadad** [comment]
@jbloom I guess my one worry is that if people see this plot, even though R looks good they may not be convinced these are good measurements 
<img width="335" alt="image" src="https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/assets/22810662/e9aaec4f-9f52-4dec-8384-7a998278d4cc">

**Comment by jbloom** [comment]
Another reasonable option is just to report the R values without showing scatter plot. Alternatively, if you increase transparency on points it will probably look better because I think there is a lot of overplotting still which visually magnifies appearance of off-diagonal points versus well correlated ones that are overplotted.
